# Site settings
title: to be defined
description: "This site contains articles about my work and other geeky stuff."
baseurl: ""
url: "http://netbe.github.io"
twitter_username: netbeatwork
github_username:  netbe
author: "François Benaiteau"
timezone: "Europe/Berlin"
# Build settings
markdown: redcarpet
permalink: pretty
pygments_options: ['lineanchors']
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      author: "François Benaiteau"



# Jekyll Picture Tag settings
gems: [jekyll-picture-tag]
pygments: true

picture:
  source: assets/images/_fullsize
  output: generated
  markup: picture
  presets:
    # Full width pictures
    default:
      ppi: [1, 1.5]
      attr:
        class: blog-full
        itemprop: image
      source_lrg:
        media: "(min-width: 40em)"
        width: 700
      source_med:
        media: "(min-width: 30em)"
        width: 450
      source_default:
        width: 350
        height: 200
    # Half width pictures
    half:
      ppi: [1, 1.5]
      attr:
        data-location: "{{location}}"
        data-active: nil
      source_lrg:
        media: "(min-width: 40em)"
        width: 400
      source_med:
        media: "(min-width: 30em)"
        width: 250
      source_default:
        width: 350
    # Self-set resolution sources. Useful if you don't want a 1:1 image size to dppx ratio.
    gallery:
      source_wide_hi:
        media: "(min-width: 40em) and (min-resolution: 1.5dppx)"
        width: 900
        height: 600
      source_wide:
        media: "(min-width: 40em)"
        width: 600
        height: 400
      source_default:
        width: 250
        height: 250
