# Site settings
title: to be defined
description: "This site contains articles about my work and other geeky stuff."
baseurl: ""
url: "http://netbe.github.io"
twitter_username: netbeatwork
github_username:  netbe
github: netbe
author: "François Benaiteau"
timezone: "Europe/Berlin"
# Build settings
markdown: kramdown
permalink: pretty
pygments_options: ['lineanchors']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
      author: "François Benaiteau"
