# Site settings
title: to be defined
description: "This site contains articles about my work and other geeky stuff."
baseurl: ""
url: "http://netbe.github.io"
twitter_username: netbeatwork
github_username:  netbe
author: "François Benaiteau"
timezone: "Europe/Berlin"
# Build settings
exclude: [vendor] # https://github.com/jekyll/jekyll/issues/2938
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough", "footnotes"]
permalink: pretty
pygments_options: ['lineanchors']
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      author: "François Benaiteau"



# Jekyll Picture Tag settings
gems: [jekyll-picture-tag, jekyll_video_tag]
highlighter: pygments

picture:
  source: assets/images/_fullsize
  output: generated
  markup: picture
  presets:
    default:
      ppi: [1, 2]
      attr:
        class: "default-pict"
      source_small:
        media: "(max-width: 20em)"
        width: "150"
      source_medium:
        media: "(max-width: 40em)"
        width: "320"
      source_default:
        width: "680"
