# Site settings
title: to be defined
description: "This site contains articles about my work and other geeky stuff."
baseurl: ""
url: "http://netbe.github.io"
twitter_username: netbeatwork
github_username:  netbe
author: "François Benaiteau"
timezone: "Europe/Berlin"
# Build settings
markdown: kramdown
permalink: pretty
pygments_options: ['lineanchors']
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      author: "François Benaiteau"

# Jekyll Image Tag settings

pygments: true

image:
  source: assets/images/_fullsize
  output: generated
  markup: picture
  presets:
    # Proportional preset
    Default:
      width: 600
    # Scaled and cropped preset
    half:
      width: 320
      height: 450
